### ISSUE TITLE
doc/copy: 2022-23 UI update (VDC, left navigation, etc.) copy changes from docs review 

### ISSUE THREAD

**Issue by jlprevatt** [RedHatInsights/curiosity-frontend#1021]
## Description
Bucket bug for various copy changes noticed in reviews of PRs related to the left nav update, early BIZ-29 VDC work, etc. tracked here:
https://docs.google.com/document/d/10VrPOJE1Uv8affxIDij0PAJYhdb87Px2BZ3lOVOFcyk/edit

**Comment by jlprevatt** [comment]
Change comment: 1
spotted in: [PR 1013](https://github.com/RedHatInsights/curiosity-frontend/pull/1013)

The copy for the new Type filter types contains a mismatch with the legend copy:
"Cloud" vs. "Public cloud"

**Comment by cdcabrera** [comment]
moved to swatch-728
