### ISSUE TITLE
Add left navigation link for 'Documentation'

### ISSUE THREAD

**Issue by jeperry** [RedHatInsights/curiosity-frontend#129]
## Description
Similar to Insights bundle, this left nav link should be after all the app pages, under a divider. It will link to the docs splash page for Subscription Watch on customer portal. Link should open in new tab.

![Screen Shot 2019-11-15 at 3 36 12 PM](https://user-images.githubusercontent.com/3761375/68974193-1ecaa880-07be-11ea-97b6-858a9f4538e6.png)

## Acceptance Criteria
- [x]  a Documentation link should appear within the left navigation
   - [x] link should open in a new tab and navigate towards, https://access.redhat.com/documentation/en-us/red_hat_insights/1.0/
   - [x] link should fall after `Getting Started` if it exists
      - there may be limitations around placement, the platform controls sequence

## Assumptions and Questions
- This is the insights docs splash page, for example.
   - https://access.redhat.com/documentation/en-us/red_hat_insights/1.0/
- related to #130

**Comment by cdcabrera** [comment]
Issue and related chroming PR
- https://github.com/RedHatInsights/insights-chrome/issues/472
- https://github.com/RedHatInsights/insights-chrome/pull/473

**Comment by cdcabrera** [comment]
Available within CI/Dev environment as of 20191126
