### ISSUE TITLE
Add left navigation link for 'Getting started'

### ISSUE THREAD

**Issue by jeperry** [RedHatInsights/curiosity-frontend#130]
## Description
Similar to link to documentation, this link goes to the 'product' page called Subscription Central which is all the curated info about the new subscription experience. 

![Screen Shot 2019-11-15 at 3 36 12 PM](https://user-images.githubusercontent.com/3761375/68974019-b2e84000-07bd-11ea-835c-83eefe762ffc.png)

## Acceptance Criteria
- [ ] a `Getting started` link should appear higher/before a `Documentation` link within the left navigation

## Assumptions and Questions
- presumed date page will be available
- it's preferred if the `Getting started` link is pushed regardless of whether there is a view/page behind it @bclarhk 
- related to #129

**Comment by cdcabrera** [comment]
@jeperry keep us appraised of when this page becomes available.

**Comment by bclarhk** [comment]
Sentence case for `Getting started`

**Comment by rblackbu** [comment]
Get Started text links to URL: https://access.redhat.com/products/subscription-central#getstarted

**Comment by rblackbu** [comment]
Per Abi.. “Get started” is fine. Let’s just put it in sentence case (So “Get Started” > “Get started”)

**Comment by cdcabrera** [comment]
@rblackbu

There was an update on the left nav regarding the documentation link towards... `https://access.redhat.com/products/subscription-central`, see
- https://github.com/RedHatInsights/insights-chrome/pull/600

Is this link still a go?
- https://access.redhat.com/products/subscription-central#getstarted

@rbernl

**Comment by rbernl** [comment]
@cdcabrera #getstarted is a tab used on other product pages which use a different UX template format.  Subscription central doesn't follow that template, so it can be omitted.

**Comment by rblackbu** [comment]
@cdcabrera The link above works for me in Chrome and Firefox. Good to go. 

The original proposal for the left nav was to be as follows:
Get Started ---> https://access.redhat.com/products/subscription-central#getstarted
Documentation ---> https://access.redhat.com/documentation/en-US/subscription_central/2019-11/

I find it odd documentation would link the user to a "Get Started" doc.

**Comment by rblackbu** [comment]
Since we are moving off /beta to production on 4/23/20 and opening subscription watch up to all users, then we don't need the two links pointing to the same document. The current documentation link in the side nav should suffice.

**Comment by cdcabrera** [comment]
Closing issue, reopen accordingly
