### ISSUE TITLE
Fix tooltip styling and behavior

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#141]
## Description
As a UI/UX designer I would like to see tooltips styled in a format other than "center aligned" and poor line height.

## Acceptance Criteria
Left align and increase line height, probably decrease padding

## Assumptions and Questions
- weight 5
- victory tooltip update
- UI/UX designer approval

**Comment by jeperry** [comment]
@bclarhk let's have Kyle Baker tackle this? What do you think. Would like for this to result in a general patternfly enhancement.

**Comment by cdcabrera** [comment]
Tooltips now have the ability to place a combination of React components, html, and styling, see #295
