### ISSUE TITLE
Research and design a solution for null data points NOT being a dip down to zero

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#166]
## Description
As a designer and end user I recognize the difference between data failures and non-existent data, and would like to see non-existent data denoted as charting gaps instead of displaying as zero.

## Acceptance Criteria
- Research ability for null data to NOT be a dip down to zero
   - [x] confirm with product management the expected display
   - [x] confirm our charting tools handle `null` vs `0` displays

## Assumptions and Questions
- **As a solution** 
   - something we had played around with early on was displaying `null` vs 0 ... victory charting does seem to handle some scenarios of null and 0, but we'd have to test it out. So in theory it just wouldn't display any data for those ticks, but they would still display. Victory, actually most graphs still need some form of "hey this is x axis value whether it exists or not"
   - we can leverage the `has_data` aspect of the RHSM/Tally response to determine "null"
   - `has_data = true` from the Tally response indicates all values supplied in the response object; cores, sockets, hypervisor_cores, physical_sockets, etc have data, "all or nothing"
   - there is an aspect of older data where actual `null` values will come across instead of zeros. we need to add an additional check for this scenario
- **Alternatives**
   - Before we implement a data point skip we should take into account...
      - the x axis point won't exist at all ... it will affect how the x axis label increment is displayed.
      - implementing a "skip" in scenarios where the starting points are non-existent creates scenarios where our granularity ranges are also affected visually
   - Do we need to account for API failures?
      - there are two potential paths with some overlap... one the GUI handles this, or two the API handles this.
         - glazing over failures from the API service itself should fallback to RHSM/Tally filling in the gaps since the GUI's insight into the API is superficial. This may require a conversation with the API team
      - adding a property or flag to the API response that says "[we made an educated guess at this data point]" would help the GUI color code, or denote, that particular data point in the future

**Comment by cdcabrera** [comment]
These are extreme examples, but they highlight what happens when combinations of null values are applied the graph/chart
    
![Screen Shot 2019-12-18 at 10 41 34 AM](https://user-images.githubusercontent.com/3761375/71200154-8b294380-2265-11ea-9911-7adcb58b4fbd.png)

      
![Screen Shot 2019-12-19 at 11 46 17 AM](https://user-images.githubusercontent.com/3761375/71200146-86fd2600-2265-11ea-8752-df818e04510d.png)

**Comment by cdcabrera** [comment]
@bclarhk just need a confirmation on whether this line of thinking/design needs to be shut down or moved back into the backlog?

**Comment by cdcabrera** [comment]
As of 20200115 this is still within the design phase. Breaking this issue into two issues, this one, research, and a separate implement issue to be noted shortly.

**Comment by bclarhk** [comment]
Currently researching possibilities. Having the backend calculate an estimated data point, but still mark it as no-data would be the cleanest way forward.

**Comment by bclarhk** [comment]
The backend ticket:
https://projects.engineering.redhat.com/browse/ENT-1964

Working on visual concepts

**Comment by bclarhk** [comment]
![image](https://user-images.githubusercontent.com/32572198/75382756-18fa5e00-58a9-11ea-8fcf-f49ac486e915.png)
apply crosshatch, gray, opacity, or some combination of visual differentiators to the area that has been estimated by the backend

**Comment by cdcabrera** [comment]
Note, applying a different colored section, or "cross-hatched" section style requires two things  
- API changes
   - https://projects.engineering.redhat.com/browse/ENT-1964
- And rendering another graph on top of the existing graphs... every graph would have 2 aspects
   - cross-hatching may not be available, a solid color may be
   - potentially duplicating every area chart will significantly increase the graph render speed. to an end user this will render "very slowly"

First round we'll focus on the "[product]: no data" portion of the area chart tooltip

**Comment by cdcabrera** [comment]
Research aspect of this is complete, issue #287 will be the continuation
