### ISSUE TITLE
Relax platform modal redirect for users missing account numbers

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#190]
## Description
As an end user the redirect modal is lacking information that I need to continue my process in viewing Subscription Watch. I'd like a relaxed platform modal redirect for users missing account numbers and to instead see the "tour" or "soon" empty state view.

## Acceptance Criteria
- [x] Users with missing account numbers should no longer receive the platform modal, but instead be redirected towards the soon/tour
- [x] Confirmation should be given by a UX/UI team member

## Assumptions and Questions
- Fastest solution is to relocate the redirect logic and have the end user redirected towards the soon/tour view
- Changing the content of the modal is the more intensive solution. May need to open a PR on the chroming repo directly to aid in getting the change pushed. It is unclear if this is Pendo related or a simple routed modal component based on query/search.
- Additional ask for turning off the toast notifications specific to the `soon`/`tour` view. 
   - Unfortunately the notifications are all or nothing, and in this scenario in order for the redirect to happen we first have to hit the API and receive the `403` which in turn generates the toast notifications and redirects.
   - Compromise solution? Once the platform modal redirect is turned off both malformed users and `403` responses will redirect towards the `soon`/`tour`. There will be no visual distinction between what error has happened. 
      - As a developer being randomly asked why something broke and given only a screenshot we're recommending a compromise solution of a single toast notification with approved copy, and possibly some copy indicator highlighting why the redirect happened. It is understood that merely redirecting towards the `soon`/`tour` should normally be that indicator. 
   - Another compromise solution, copy adjustments to the `soon`/`tour` highlighting the error.

**Comment by rbernl** [comment]
The problematic popup with 'not now' has no relation to Pendo. It is from the CRC platform and  is thrown "when the 'getUser' response from the platform returns nothing/empty/null/blank/broken.

**Comment by cdcabrera** [comment]
@rbernl agreed, the `getUser` logic is within the Curiosity codebase, this should help breakdown some of the current prod-beta display logic

- https://github.com/RedHatInsights/curiosity-frontend/pull/170
