### ISSUE TITLE
UX/Design for dashboard graph card behavior. Tooltip behavior included

### ISSUE THREAD

**Issue by bclarhk** [RedHatInsights/curiosity-frontend#23]
## Feature Description
As a user it would be helpful to have a tooltip display important graph details when the bar chart/graph is hovered over.

## Storyboard
https://marvelapp.com/61fh138/screen/58583020

![Screen Shot 2019-06-28 at 3 07 55 PM](https://user-images.githubusercontent.com/3761375/60365377-8c646c80-99b6-11e9-9c57-e46533bdb671.png)

**Comment by priley86** [comment]
should be doable... will take a gander. 🔍
