### ISSUE TITLE
Separate the CI and QA beta/stable environment deploys

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#259]
## Description
As a developer I need to separate the CI and QA beta/stable environment deploys by Git branch now that the API is deploying to the QA environment.
   - QA = QA beta and stable
   - CI = CI beta and stable

## Assumptions and Questions
- Currently CI = CI beta and QA beta, QA = CI stable and QA stable
- As of 20200813 this is low priority since the addition of the "stage" environment is introducing variations in workflow on the API side of things. Need to let it play out before approaching this.

**Comment by cdcabrera** [comment]
Holding on this as of 20200504 until the API is fully setup in the QA environment.

**Comment by ntkathole** [comment]
This make sense to me and it works for QE.

Overall I see the picture as follows: 

**1. ci = ci-stable/ci-beta**
This is where devs can do whatever they want (playground for devs) and QE can use this as reference for working on future automation and also for each pull request manual testing. This is a place of collaboration and working with devs closely. Also our automation has capability to run on CI env whenever required for regression testing.

**2. qa = qa-stable/qa-beta**
This is where QE automation will run. Release should be aligned with backend release to qa env. Ideally we should try to have code as early as possible to this branch.

**3. stage = stage-stable/stage-beta**

**4. prod-beta = prod-beta**

5. prod OR master = prod-stable

**Comment by cdcabrera** [comment]
Awesome @ntkathole ! This aligns perfectly with the direction we want to head. And we are fully onboard with renaming `master` -> `prod`. Couple of things this'll help with
- It'll help eliminate confusion around `master` on platform repos being considered `ci/dev`
- It'll help with switching "default" branches, so dev PRs coming into the code will automatically fill in "ci"

**Comment by cdcabrera** [comment]
Mostly resolved with #956
