### ISSUE TITLE
Add FAQ link in Subscription Watch UI, left nav or alternative location

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#302]
## Description

As user I would like to see a link to the Subscription Watch FAQ in the left navigation under Documentation.

Alternative solutions are acceptable. The idea is to provide a resource to customers directly from the UI so they don't have search.

## Acceptance Criteria
- [x] UI/UX
   - working as intended
   - [x] accepted request
- [x] Update Bugzilla, https://bugzilla.redhat.com/show_bug.cgi?id=1831349
- ~Activate the left nav with a FAQ Link, within platform standards~ As of 20200717 Pendo's resource center concept may replace the link. This fits within the request for an "alternative solution"

## Assumptions and Questions

- FAQ resource is located here, `https://access.redhat.com/articles/4897921`
- Alternative solutions are acceptable
- Relates #305

**Comment by rblackbu** [comment]
Hold to adding FAQ to the side navigation. There is an upcoming project to have Pendo's Resource Center available in Subscription Watch. Displaying the FAQ in the widget might make more sense.

**Comment by rblackbu** [comment]
Video recording to show FAQ in Resource Center https://www.loom.com/share/a4c528e398cd4e5e9d993442c464fbcf
