### ISSUE TITLE
Apply a sub heading description in view, above graph/chart

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#305]
## Description
As an end user I would like to know what Subscription Watch is without having to search for information. Applying descriptive paragraph would help

## Acceptance Criteria
- [x] Initial UI/UX
- [x] Implement
   - [x] Implement text
   - [x] Implement ~"learn more..." ... this facet is on hold as of 20200717~ FAQ link in place of "Learn more..."

## Assumptions and Questions
- Additional reference, https://www.patternfly.org/v4/documentation/react/demos/pagelayout/default-nav
- Learn more link is related to... #302 Display a "FAQ" like link would also work 
   - @rblackbu
- Messaging for specific views
   - **Openshift** - View your Red Hat OpenShift usage measured by CPU cores or sockets, depending on your subscriptions.
   - **RHEL** - View your Red Hat Enterprise Linux usage according to physical, virtual, and public cloud socket usage.

![Screen Shot 2020-07-17 at 12 33 39 PM](https://user-images.githubusercontent.com/3761375/87809731-db7f7880-c829-11ea-8e4a-d16e7c90031a.png)

**Comment by rblackbu** [comment]
**For RHEL use text:**
View your Red Hat Enterprise Linux usage according to physical, virtual, and public cloud socket usage. Learn more about Subscription Watch reporting
URL:  https://access.redhat.com/documentation/en-us/subscription_central/2020-04/html/getting_started_with_subscription_watch/con-how-does-subscriptionwatch-show-data_assembly-opening-subscriptionwatch-ctxt/

**Comment by rblackbu** [comment]
**For OpenShift use text:**
View your Red Hat OpenShift usage measured by CPU cores or sockets, depending on your subscriptions. Learn more about Subscription Watch reporting
URL: https://access.redhat.com/documentation/en-us/subscription_central/2020-04/html/getting_started_with_subscription_watch/con-how-does-subscriptionwatch-show-data_assembly-opening-subscriptionwatch-ctxt/

**Comment by cdcabrera** [comment]
@zanewoodfin 
Need to confirm, then possibly adjust, the margin-bottom for the H1 aligns to 
- https://www.patternfly.org/v4/documentation/react/demos/pagelayout/default-nav
