### ISSUE TITLE
[Regression] Activate subscription watch page not displayed for not optin user

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#307]
## Description
Activate subscription watch page not displayed for not optin user or optin deleted user. A blank page without (faded) graph shown on user which is not optin.

### Expected behavior
Activate subscription watch page should display.

#### Steps to reproduce
1. Create new user or delete optin for existing user.
2. Navigate to https://ci.cloud.redhat.com/beta/subscriptions/rhel-sw/x86

### Additional context, version info
Looks like regression from #306 

![Screenshot from 2020-06-09 17-11-27](https://user-images.githubusercontent.com/16951913/84143482-4c39b500-aa74-11ea-838f-490a116b27cb.png)

**Comment by cdcabrera** [comment]
@ntkathole good catch! Fix has been added to the CI-beta environment/path if we can get a regression test confirmation.

Appears a minor condition update was needed, see #308 for details.

**Comment by cdcabrera** [comment]
Thinking it may be good if we start thinking about some form of automation checks that possibly happen...
- right when a PR is opened, in addition to Travis, and with the understanding it would increase the time of PR checks
- and/or automatically open bug issues against the repo, which fits more in line with how the existing regression tests are set up

**Comment by ruda** [comment]
Hi, I verified today with my test account, removed the opt_in from it and then after enableing it and refresh I've got the graph as expected. So it is working as expected now.

**Comment by ntkathole** [comment]
Thanks @cdcabrera for quick fix. Its working fine now. :+1:
