### ISSUE TITLE
Tooltip don't show some middle entries for Weekly/Monthly/Quarterly granularity

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#318]
## Description
While moving the cursor hover the graph from left to right with Weekly/Monthly/Quarterly granularity, some of the middle entries are missed from tootip information. This happens on 1920*1080 display size.

### Expected behavior
Tooltip should read all 

#### Steps to reproduce
1. Open curiosity UI
2. Move cursor from left to right hover the graph and notice date range.

### Additional context, version info
This issue is not new and present in production env as well.
If I make the graph screen smaller, it reads correctly. 
 In below gif, Date range shown after 5 April -12 April is 26 Apr - 3 May, middle entries are not shown while hover.

![hover](https://user-images.githubusercontent.com/16951913/84782393-963b1180-b005-11ea-94e1-2473c242a7c3.gif)

**Comment by cdcabrera** [comment]
@ntkathole patch has merged into CI-beta, confirmation when you're ready.

**Comment by ntkathole** [comment]
Changes looks good. Issue fixed. Thanks @cdcabrera :)

**Comment by ntkathole** [comment]
@cdcabrera I am hitting this issue again but this time it is only for when SLA filters are applied. 
Most of the time when Self-support SLA and granularity other than daily.

**Comment by cdcabrera** [comment]
Hi @ntkathole 

We were unable to recreate the issue you've found we tested...
- browsers
   - Firefox v68.9.0 esr
   - Chrome, latest
- os
   - mac osx
- screen dimensions
   - 1700 px width
   - 930 px width
- Subscription Watch filters
   - SLA, Self Support
   - Granularity, Weekly, Monthly, and Quarterly

What we did notice is that regardless of screen width dimensions there is some offset between the way the x-ticks are generated and how the tooltip displays, and while it is "quirky" on how smooth it displays, especially on Weekly and Quarterly granularities, there didn't appear to be any missing tooltips. 

#### Weekly
![Jun-23-2020 11-16-39](https://user-images.githubusercontent.com/3761375/85423295-84e19000-b544-11ea-8e61-04f3b1507261.gif)
#### Quarterly
![Jun-23-2020 11-14-55](https://user-images.githubusercontent.com/3761375/85423384-a17dc800-b544-11ea-9c60-f8ae8ed0e87d.gif)

We also did some general screen recordings... we'll post the originals to our Slack conversation, seem to be a little large for Github, here's the compressed ones (little hard to see)

#### Weekly
![Jun-23-2020 11-31-26](https://user-images.githubusercontent.com/3761375/85423977-5d3ef780-b545-11ea-9459-9bae8a98ee8d.gif)


#### Monthly
![Jun-23-2020 11-30-05](https://user-images.githubusercontent.com/3761375/85424043-7182f480-b545-11ea-8405-bc0b6c7d6cd2.gif)




#### Quarterly
![Jun-23-2020 11-30-46](https://user-images.githubusercontent.com/3761375/85424001-63cd6f00-b545-11ea-878b-84977dec7090.gif)

**Comment by cdcabrera** [comment]
### Appears this issue still pops up...
As of 20200623
- On Linux based machines this was recreated with a little more consistently using
   - Firefox 68.8 esr
   - Chrome 81
- And on Mac OS we were able to recreate the issue a couple of times, but after resizing the browser the issue no longer presented itself
   - Firefox 68.9 esr

#### Educated guess?
We acknowledge this may be an issue, just not super consistent on non-linux machines. The behavior
- Looks like it's using cached code, but we can't know for certain until we pull out the browser window global the GUI/Curiosity attaches and we do a comparison on the git hash. 
- Another facet to the issue looks like it still has to do with certain browser/screen dimensions, but inconsistently given that a simple browser resize on Mac OS seemed to fix the issue.

#### Next steps
1. With agreement from QE we'll monitor this over the next sprint to see if the issue pops up again
1. We'll move the patch from #324 into CI-stable and QA-stable 
   - this relates to parts of the CI-beta environment being updated, said environment is currently going through platform chroming/resource updates and we can eliminate a possible factor by syncing 


#### Extreme next steps
We reevaluate the use of the chart/graph API we're currently using, again =). We had already investigated replacing the tooling with C3, and this still comes across as a viable alternative with a fraction of the issues and amount of code. We would have to bring the draft implementation up to spec. We have a project task setup to bring C3 up to par with our Victory implementation.

**Comment by ntkathole** [comment]
@cdcabrera as you said, it seems like it was using cached code. I haven't seen any failure in our tests since 27th June on QA-Beta. We can close this issue.

**Comment by cdcabrera** [comment]
Awesome, good to hear!
