### ISSUE TITLE
Implement platform component for an application level maintenance mode

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#320]
## Description
As a designer I should investigate a pf based solution that compliments the Platform level maintenance messaging to avoid overlap and confusion.

As a developer I need to develop a solution for application level maintenance mode for scenarios where coordination between API, Platform, and GUI can happen "awkwardly"

As an end-user it would be helpful to understand when the application is not-functioning to avoid confusion and help me not open issues against non-existent problems.

Maintenance notification
https://docs.google.com/document/d/1VLs7vFczWUzyIpH6EUsTEpJugDsjeuh4a_azs6IJbC0/edit

SVG
https://pnt.redhat.com/pnt/p-15530715/Icon-Red_Hat-...Black-RGB.svg

Component:
https://github.com/RedHatInsights/frontend-components/blob/master/packages/components/src/Components/Maintenance/Maintenance.js

## Acceptance Criteria
- [x] Determine the best location to place the maintenance mode component. 
    - authentication, or as a fallback the app component.
    - determine if locale strings is an option. i.e. moving strings to our en-US.json if unavailable
    - if strings are required work with UI/UX, the API team, and CCS to determine required copy
- [x] Currently there is no API endpoint associated with activating this mode
   - confirm/follow up with API team on the related Jira task
   - if the API is unavailable determine if a temporary disable would benefit us, similar to the existing `disables` located in our core dotenv `.env`

## Assumptions and Questions
- Will copy will be generated from the API, or will the API continue with error codes?
- The Auth component brings everything together, however the `app` component may be a better location. Reasons for consideration should include an "application level" maintenance mode would still give us access to RBAC and general platform permissions
- Unclear how often this will happen. But given the recent RBAC changes it would helpful to an end user, and help avoid unnecessary bug filings
- Existing design, and a plan at the Platform level to make this a shared component most likely through the Frontend-Components repo.
![image](https://user-images.githubusercontent.com/32572198/87810825-98bea000-c82b-11ea-8f09-393f21c05e5d.png)

**Comment by cdcabrera** [comment]
As of 20200717 @rblablu hourglass icon research. if you can locate said icon, super helpful!

**Comment by rblackbu** [comment]
Replace icon with the latest 'hourglass' style. See the attached reference. 

Download brand icon library here --> [
<img width="567" alt="Screen Shot 2020-07-17 at 12 13 37 PM" src="https://user-images.githubusercontent.com/25234746/87808347-8b9fb200-c827-11ea-992c-5394d45a89e4.png">
](https://www.google.com/url?q=https://pnt.redhat.com/pnt/b-13318695/NEW_Standard_icons&sa=D&ust=1586467269333000&usg=AFQjCNFCksNYFLyab4KpycUjZuN2s0WTDA)

**Comment by rblackbu** [comment]
https://pnt.redhat.com/pnt/b-13318695/NEW_Standard_icons?login=1595002712

**Comment by cdcabrera** [comment]
As of 20200805 this component is located here, https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/Components/Maintenance

**Comment by zanewoodfin** [comment]
As of 2020-08-31, work has not yet been started on an API-based way to enter maintenance mode, so we probably need to move that into Phase 5.

**Comment by cdcabrera** [comment]
Phase 5 iterative issue has been created, see #404
