### ISSUE TITLE
Outline a branching process for "one-off" releases

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#338]
## Description
The goal of the basic environment branches doesn't encompass one-off/random requests from stakeholders.

Research and update the `contributing.md` and outline a process for "unblocking" environments when special requests are made.

## Acceptance Criteria
- [ ] `Contributing.md` has been updated with the "one-off" process

## Assumptions and Questions
- This should look at creating a temporary placeholder branch once QE has confirmed the changes have passed. QE should be consulted on this.
- Additional QE involvement may be needed to confirm they are primarily focused on testing QA, and minimally running regression tests in CI/dev. 
   - This isn't ideal but from there we may need to determine if QA-beta and QA-stable need to be broken out further.
- Relates #396

**Comment by ntkathole** [comment]
I think we have to consider https://github.com/RedHatInsights/curiosity-frontend/issues/259 as well while working on this.

**Comment by cdcabrera** [comment]
Mostly resolved, latest updates from #956
