### ISSUE TITLE
Blank page for not opt in user

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#342]
## Description

User who didn't activate subscription watch see blank page rather than activate subscription watch page.

Environment : CI-Beta/QA-Beta

Regression from #337 

### Expected behavior

User should see activate subscription watch page.

![Screenshot from 2020-07-16 12-23-54](https://user-images.githubusercontent.com/16951913/87637108-60519000-c75f-11ea-9fde-69f4016d7b59.png)

#### Steps to reproduce
1. Create new user or delete opt in for exiting user
2. Visit subscription watch.

### Additional context, version info
![Screenshot from 2020-07-16 12-19-56](https://user-images.githubusercontent.com/16951913/87637086-592a8200-c75f-11ea-85eb-ca9fa54c69a2.png)

```
react-dom.production.min.js:244 Uncaught (in promise) Error: A React component suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
    in Unknown
    in t
    in j
    in withRouter(j)
    in n
    in withI18nextTranslation(n)
    in S
    in withRouter(Connect(withI18nextTranslation(n)))
    in n
    in n
    in S
    in withRouter(Connect(n))
    in t
    in t
    in c
    at rs (react-dom.production.min.js:244)
    at Ju (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Vo (react-dom.production.min.js:122)
    at Ko (react-dom.production.min.js:123)
    at Go (react-dom.production.min.js:122)
    at es (react-dom.production.min.js:240)
    at Object.notify (Subscription.js:19)
    at e.t.notifyNestedSubs (Subscription.js:92)
```

**Comment by cdcabrera** [comment]
This is related to #328

**Comment by cdcabrera** [comment]
@ntkathole ready for confirmation. fixes have been moved into ci-beta

**Comment by ntkathole** [comment]
Awesome.. This fixes the issue @cdcabrera
