### ISSUE TITLE
Show clusters in openshift based on sockets and cores

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#383]
## Description
Currently openshift system table displays all clusters Independent of filter selected is socket or cores in GUI. We should display only those systems/clusters which are contributing to what is shown in graph. 

related to #10 

### Expected behavior

When socket is selected only those clusters will display which are contributing to socket and same for cores.

#### Steps to reproduce
1. Navigate to openshift subscription watch page.
2. See system table lists clusters for both sockets and cores.
 

### Additional context, version info

![Screenshot from 2020-08-21 12-17-36](https://user-images.githubusercontent.com/16951913/90861788-f9507800-e3a9-11ea-81ae-b83614c9248e.png)

**Comment by cdcabrera** [comment]
As of 20200821 a Jira related issue ENT-2775 `Add a hosts systems inventory filter for "unit of measure"` has been opened

**Comment by cdcabrera** [comment]
@ntkathole the patch is now available for confirmation within the CI-beta environment

**Comment by ntkathole** [comment]
@cdcabrera there is typo in fix `umo Vs uom`. 

Query should 

`https://qa.cloud.redhat.com/api/rhsm-subscriptions/v1/hosts/products/OpenShift%20Container%20Platform?limit=100&offset=0&uom=sockets`

But it is

`https://qa.cloud.redhat.com/api/rhsm-subscriptions/v1/hosts/products/OpenShift%20Container%20Platform?limit=100&offset=0&umo=sockets`

**Comment by cdcabrera** [comment]
@ntkathole updates around the rename should be available for retesting when you're ready

**Comment by cdcabrera** [comment]
- 2/2  of the remaining UI/UX blocking for #10 
- 2/2 see #400

**Comment by ntkathole** [comment]
@cdcabrera Issue is fixed. Thank you :tada:
