### ISSUE TITLE
Differentiate between public cloud and virtual system in system table

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#389]
## Description
Currently public cloud system is also shown as virtual in infrastructure column. This may create confusion when end user tried to calculate tally based on system table. Graph shows public cloud system usage differently than virtual system usage and also API has  'measurement_type'  based on which public cloud systems can be differentiate, but there is no way in UI to differentiate between them.

**API :**
```
{'cores': 24,
           'display_name': '62078ddc-8bdb-49c9-93af-b48e0a00768f',
           'hardware_type': 'VIRTUAL',
           'insights_id': '7c2c5868-c11d-4601-9b70-a3da1205a6ba',
           'inventory_id': '62078ddc-8bdb-49c9-93af-b48e0a00768f',
           'last_seen': datetime.datetime(2020, 8, 24, 4, 32, 5, 262810, tzinfo=tzutc()),
           'measurement_type': 'AZURE',
           'number_of_guests': None,
           'sockets': 1,
           'subscription_manager_id': 'ccae7d2b-0ae1-425e-8629-84348f034f3e'},
```

**GUI :**
![Screenshot from 2020-08-24 10-11-30](https://user-images.githubusercontent.com/16951913/91004585-3b6bfa80-e5f2-11ea-98b7-a102aa6c7c37.png)

### Expected behavior
Infrastructure type should be public cloud (not virtual) for public cloud usage.

#### Steps to reproduce
1. Have a public cloud usage.
2. See system table shows all systems "virtual"

### Additional context, version info

Related to #10 #393

**Comment by cdcabrera** [comment]
As of 20201005 API is planning to push up to dev this week

**Comment by cdcabrera** [comment]
@ntkathole some of the updates on the API side made it to CI we're aware that the translation strings aren't carrying over in that environment

![Screen Shot 2020-10-15 at 4 18 04 PM](https://user-images.githubusercontent.com/3761375/96181495-1749dd00-0f02-11eb-9a69-c86c09d6876d.png)

Appears instead of being called "virtual" they're now called "virtualized" =)

**Comment by ntkathole** [comment]
Fixed! Now we have public cloud type in system table.
