### ISSUE TITLE
Inventory display for cloud providers

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#393]
## Description
As a designer I need to consider how cloud providers should be displayed within an inventory listing.

## Acceptance Criteria
- [x] Mock research and design

## Assumptions and Questions
- Relates #389 #431 #483

**Comment by cdcabrera** [comment]
As of 20201104 additional updates were requested, a round 2. @bclarhk @rblackbu do we consider this issue complete or should we retain it for the additional updates around duplicates? (there is an existing issue, #431 )

**Comment by bclarhk** [comment]
Ignore the Operating system column (for now)
https://marvelapp.com/prototype/eih495e/screen/71576870
