### ISSUE TITLE
Inventory list needs to reset offset when paging limit increased

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#400]
## Description
Appears to be a bug, the offset/page doesn't reset when the paging limit is increased. this can lead to an API 4XX level error

### Expected behavior
The GUI shouldn't break when increasing the paging limit.

#### Steps to reproduce
1. Locate an account with over 10 inventory listings
1. navigate to the 2nd offset/page with the paging controls
1. select to increase the paging display limit
1. error should be throw and the GUI displays an error state

### Additional context, version info
- 1/2  of the remaining UI/UX blocking for #10 
- 2/2 see #383 

<img width="987" alt="Screen Shot 2020-08-28 at 1 30 38 PM" src="https://user-images.githubusercontent.com/3761375/91598593-68dae000-e933-11ea-9ca6-67d9e7294eff.png">

**Comment by ntkathole** [comment]
Good catch @cdcabrera

**Comment by cdcabrera** [comment]
@ntkathole if you could also confirm this has been resolved before we close this one down, that would be awesome!

**Comment by ntkathole** [comment]
@cdcabrera This is still an issue. We should also reset offset when new filter applied. Here are steps:

1. Have 100+ RHEL hosts and out of which only around 20 are "premium".
2. Navigate to RHEL page.
3. Navigate to last page of system table.
4. Select SLA filter "Premium".

**Comment by cdcabrera** [comment]
@ntkathole updates around reseting the paging when manipulating filters should be in CI-beta when you're available to confirm

**Comment by ntkathole** [comment]
@cdcabrera There is still issue for openshift cores/socket filter. Here are steps:
1. Have openshift clusters based on sockets less than openshift clusters based on cores.
2. Navigate to openshift page.
3. Navigate to last page of system table.
4. Select "sockets" in filter.

**Comment by cdcabrera** [comment]
Looks like we need a better way of handling this, investigating something a little bit more centralized so when we add additional filters we don't need to update multiple locations of paging resets.

**Comment by cdcabrera** [comment]
Third round for the win, I hope =)

@ntkathole updates around reseting the paging when manipulating filters should be in CI-beta when you're available to confirm

**Comment by ntkathole** [comment]
@cdcabrera Issue is fixed now. Thank you :tada:
