### ISSUE TITLE
Reset offset while navigating between RHEL pages

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#421]
## Description
Reset offset while navigating between RHEL pages.

### Expected behavior
We also need to reset offset while navigating between RHEL pages. 

#### Steps to reproduce
1. Have some hosts with IBZ z systems or other architecture. 
2. Navigate to RHEL All page.
3. Navigate to last page.
4. Navigate to RHEL IBM z systems or other architecture page.

### Additional context, version info
![Screenshot from 2020-09-14 13-01-42](https://user-images.githubusercontent.com/16951913/93057436-8924d180-f68b-11ea-9e1f-f3f4ba14558a.png)

**Comment by cdcabrera** [comment]
@ntkathole updates are within the QA branch (QA-stable, CI-stable) and available for testing, see PR #423 for additional notes.

The behavior for the paging has altered slightly
- Product architectures/sub-categories are fully independent in their limit and page offset. 
      - ALL architectures/sub-categories should have limit and offset reset by the following filter selections and clearing: SLA, USAGE, UOM
         - There is the additional facet of this resetting the product/viewId limit and offset, this is expected. However, we've built into the Platform behavior of each product reseting ALL state when a user moves between products. **This is a note in the event future left menu changes alter current Platform behavior.**
      - ALL architectures/sub-categories should maintain their own page limit and offset unless otherwise reset. This means if a user moves between architectures/sub-categories GUI state should restore a prior page limit selection, unless it was reset

**Comment by ntkathole** [comment]
@cdcabrera Looks good now. Issue fixed and working as expected.
