### ISSUE TITLE
Navigation panel not showing openshift page as currently selected

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#422]
## Description
We display selected page as blue ticked in navigation panel. But looks like something is changed recently in core or in NPM updates that caused  navigation panel not showing openshift page as currently selected.

**Reproducible in CI-Beta/QA-Beta only.**

### Expected behavior
Page should mark as currently selected page.

#### Steps to reproduce
1. Navigate to https://qa.cloud.redhat.com/beta/subscriptions/rhel-sw/all 
2. Click on "Red Hat OpenShift" in navigation.
3. See page not marked as currently selected.

### Additional context, version info
![Screenshot from 2020-09-15 11-34-14](https://user-images.githubusercontent.com/16951913/93172901-593c0380-f749-11ea-8e78-fae29a5c455c.png)

**Comment by cdcabrera** [comment]
@zanewoodfin just need to determine if the recent package updates are a correlation or cause. Platform is/was doing their monthly chrome updates this could part of the cause.

1. confirm what platform updates have taken place, possibly confirm on another app/gui, possibly reach out in Slack
   - if this is the cause simply reply back to this chain with a comment
2. if the platform updates come back negative. investigate the NPM updates that were moved to CI-beta last week. It may be easier to roll them back one at a time starting with the patternfly updates.
   - if this is the cause we can temp roll a package back with a PR and then figure out what to do from there

**Comment by zanewoodfin** [comment]
On 09/16 I informed platform team of the issue and they are looking into it.  This issue was likely the result of them recently "tweaking some nav things to increase performance".

**Comment by cdcabrera** [comment]
As of 20200925 we can no longer recreate this, appears to be fixed

@ntkathole can you confirm?

![Screen Shot 2020-09-25 at 8 29 05 PM](https://user-images.githubusercontent.com/3761375/94325744-dc413300-ff6d-11ea-9e8d-37a5124e3e98.png)

![Screen Shot 2020-09-25 at 8 28 58 PM](https://user-images.githubusercontent.com/3761375/94325756-f24ef380-ff6d-11ea-932a-90594b9bcf04.png)

**Comment by ntkathole** [comment]
Yes, it is fixed now. Thanks!
