### ISSUE TITLE
Side drawer documentation

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#452]
## Description
As a developer I need to activate documentation in a side drawer to aid in UX.

## Acceptance Criteria
- ...

## Assumptions and Questions
- New CCS DB needs to be up and running for this to be a viable feature

**Comment by rblackbu** [comment]
For reference only: https://marvelapp.com/prototype/25jgcc1g

**Comment by dvoss-rh** [comment]
I'm dropping this link here for easy of access. @cdcabrera I've created this spreadsheet to drop the knowledge I've gathered together, including the API calls to the new tooling approach.

**Comment by cdcabrera** [comment]
Resolved with Pendo documentation. As of 202212 reevaluated, reopen as necessary on the appropriate board
