### ISSUE TITLE
Hypervisor should display as "hypervisor" or "virtual" infrastructure type in system table

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#468]
## Description
We consider tally of hypervisor in **virtual** bucket but system table shows **physical** . (Previously we used to show as **Hypervisor**)

**Reproducible only in CI-Beta.**

### Expected behavior
Hypervisor should show as "hypervisor" or "virtual" not physical.

#### Steps to reproduce
1. Have hypervisor in account
2. See system table

### Additional context, version info
![Screenshot from 2020-10-21 18-49-03](https://user-images.githubusercontent.com/16951913/96726269-68a90f00-13cf-11eb-8b0a-ad8da44c92a9.png)

![Screenshot from 2020-10-21 19-06-00](https://user-images.githubusercontent.com/16951913/96727273-8034c780-13d0-11eb-9d5c-34596e3b6b81.png)

**Comment by rblackbu** [comment]
Hey Nikhil, we are taking a look at this now and will post a direction by the end of the day. Thanks!

**Comment by cdcabrera** [comment]
As discussed and indicated by UX/UI, specifically regarding the "hypervisor" display

1. If it's a hypervisor, it’ll have a "chevron twistie" and a number of VMs bubble

And there are additional updates around the display meant to align to the graph and associated tooltips
1. the inventory column formally called "Infrastructure" is now called "Type
1. the guests inventory column formally called "Name" is now called "VM name"

**Comment by cdcabrera** [comment]
Updated discussion with UX/UI and API, as an agreed upon iterative "next steps" the GUI will be
1. Updated to use the Measurement Type column from the API
   - The API will review replacing the Cloud Providers currently in the response to simple be "CLOUD"
   - The API will review replacing the Hypervisor currently in the response with the word "VIRTUAL"
   - The GUI will display the word "Hypervisor" until the API is updated
   - The GUI will attempt to temporarily replace the Cloud Providers coming through in the response with the phrase "Public Cloud"... we may simply pass the data for display
1. The acronym "VM" will be replaced in two locations to say "Guests [TOTAL]" and "Guest name" similar/same to the "pre" VM display
1. The GUI will hold on displaying the column header change "Subscribed sockets"

@bclarhk @rblackbu  @jlprevatt

**Comment by bclarhk** [comment]
This looks like a good iterative path forward.

**Comment by cdcabrera** [comment]
Per the requested updates, see PR 

Primary gotcha is lack of sorting on "measurement type"
<img width="618" alt="Screen Shot 2020-10-28 at 2 11 51 PM" src="https://user-images.githubusercontent.com/3761375/97478649-9b02c100-1927-11eb-9984-a90332e4d254.png">


![Screen Shot 2020-10-28 at 2 11 11 PM](https://user-images.githubusercontent.com/3761375/97478553-7dcdf280-1927-11eb-8a52-c458a54ab5f3.png)

**Comment by bclarhk** [comment]
That sounds like "bad things could happen." We need to have [ measurement_type ] added to HostReportSort.

**Comment by cdcabrera** [comment]
@ntkathole this appears to be resolved, short of any new issues that may be appearing, correct?

**Comment by ntkathole** [comment]
Yes, it is resolved. We can close this! Currently we are showing it as Virtual. In future, we may reintroduce "Hypervisor" as a part of https://issues.redhat.com/browse/ENT-3210, which we need to track as separate issue.
