### ISSUE TITLE
Hide SAP/global filter from swatch

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#473]
## Description
Subscription watch page shows SAP/global filter to tag. I think it is not needed in subscription watch app.

Platform issue - https://issues.redhat.com/browse/RHCLOUD-10185 

### Expected behavior

```
Karel Hala added a comment - 33 minutes ago - edited
We've enabled global filter on all insights application and since subs watch is partially under insights bundle you are seing this. If you don't want to see it you have to disable this feature in your application https://github.com/RedHatInsights/insights-chrome#toggle-global-filter-on-certain-pages

EDIT: Just call `insights.chrome.hideGlobalFilter()` in your application when it first renders and you should be good go.
```

#### Steps to reproduce
1. Navigate to curiosity on QA/QA-beta

### Additional context, version info
![Screenshot from 2020-10-23 12-19-06](https://user-images.githubusercontent.com/16951913/96979630-cc9d1600-153c-11eb-8a14-dec525490206.png)

**Comment by cdcabrera** [comment]
We'll go ahead and aim to align this to the push we were aiming for on 10/26. Our side of things may be delayed dependent on "deactivating" this piece

**Comment by ntkathole** [comment]
**Exact steps to reproduce:**
1. Login with swatch-satellite-user to https://qa.cloud.redhat.com/
2. Navigate to subscription watch (Global filter will not be visible)
3. Navigate to "Red Hat Insights" using application switcher from left navigation panel. 
4. Select "Patch" from navigation.
5. Apply any tag from global filters.
6. Navigate to subscription watch using application switcher from left navigation panel.

![globfilter](https://user-images.githubusercontent.com/16951913/97144009-bafc7e00-1789-11eb-858a-05219e5ab9b5.gif)

**Comment by cdcabrera** [comment]
Checked it out, currently still unable to recreate even with the steps listed. We'll look and see if some of the design team, @bclarhk @rblackbu ,  members can recreate this, wondering if browser is playing a part...


And in the spirit of Monday AM... we're once again seeing one of our older errors that we had squashed a ways back pop back up, something to do with how the redirect and `app name` are being handled on the Platform chrome side when the app is forced to redirect and the Platform dumps a user on ... `...com/subscriptions` 
- https://github.com/RedHatInsights/curiosity-frontend/issues/179

**Comment by bclarhk** [comment]
I couldn't reproduce this on my Mac running Firefox 81.0.1

**Comment by cdcabrera** [comment]
Double checked FF 68.10 esr, unable to recreate there too

**Comment by ntkathole** [comment]
@cdcabrera I checked now again and **now** its not reproducible on my side. Not sure what was the actual cause :/

**Comment by ntkathole** [comment]
Closing as no longer reproducible after above fix and release in prod.
