### ISSUE TITLE
RFE: Filter hosts in the system table

### ISSUE THREAD

**Issue by kahowell** [RedHatInsights/curiosity-frontend#475]
## Description

As a developer I need to activate the UI/UX for filter hosts in the system table so that I can quickly find systems.

## Acceptance Criteria
- [x] Verify that users can filter hosts in the system table

## Assumptions and Questions
- This will need API changes (https://issues.redhat.com/browse/ENT-3195)
- Design story #476

**Comment by cdcabrera** [comment]
As of 202102 this was moved to the GUI prod-beta env, see #571 and #568
