### ISSUE TITLE
Filter inventory by Display Name

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#476]
## Description

As a UI/UX person I need to consider large numbers of inventory entries and the user ability to filter by a string associated with the inventory Display Name.

## Acceptance Criteria
- [ ] Storyboard or screenshot confirmation
- [ ] Toolbar component for tabs, relates towards #407 
   - Inventory level toolbar with display name filter
   

## Assumptions and Questions

- Consider creating a "widget" a self contained form field capable of updating state standalone
- Should this be a separate toolbar specifically for inventory, 3 toolbars?
- Should this apply to the global app search and apply to the Tally (graph display) as well or be limited to inventory display only
- Dev story #475

**Comment by rblackbu** [comment]
![Uploading Screen Shot 2020-11-05 at 11.50.24 AM.png…]()

**Comment by rblackbu** [comment]
<img width="1230" alt="Screen Shot 2020-11-05 at 12 02 19 PM" src="https://user-images.githubusercontent.com/25234746/98272572-3ebf2300-1f5f-11eb-9bb0-ff2a5169409f.png">

**Comment by rblackbu** [comment]
<img width="1308" alt="Screen Shot 2020-11-05 at 11 50 24 AM" src="https://user-images.githubusercontent.com/25234746/98272704-60200f00-1f5f-11eb-9894-ce4640a6bc3c.png">

**Comment by cdcabrera** [comment]
Intended behavior, confirmation
First round
- the filter should always display
- should only be the input field with magnifying glass
- still need input on "clearing" the field

API wise
- looking at doing an "autocomplete" with 2-3 characters. We should ask API team for input

PF wise
- still looking for the Patternfly autocomplete example
