### ISSUE TITLE
replace IBM with ALIBABA cloud

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#481]
## Description
The supported values for cloud provider are [[AWS, GOOGLE, ALIBABA,  AZURE]](https://github.com/RedHatInsights/rhsm-subscriptions/blob/038ae846c075d58a4152a8819163d8d20b661320/src/main/java/org/candlepin/subscriptions/db/model/HardwareMeasurementType.java#L30 ) 

### Expected behavior
Replace IBM with ALIBABA at https://github.com/RedHatInsights/curiosity-frontend/blob/ci/public/locales/en-US.json#L55

**Comment by cdcabrera** [comment]
@ntkathole change has been added, if you can confirm

**Comment by ntkathole** [comment]
Fixed!
