### ISSUE TITLE
Update the Sockets column header copy

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#483]
## Description
As a developer I need to update the Sockets column header string

## Acceptance Criteria
- [x] Sockets column header changed to "Subscribed sockets"

## Assumptions and Questions
- column truncation may be an issue it may benefit us to consider altering the order of the words
- review multiline column header display, relates #472 
- Considering this an "iterative update" until informed otherwise. As of 202010 the current "sockets" column is not representative of "Subscribed sockets"
- investigate wrapping

**Comment by dozdowski** [comment]
"Sockets subscribed" is fine as well, per Ben's comment
