### ISSUE TITLE
Type column on openshift page

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#488]
## Description
With recent change from hardware type to measurement type, system table for openshift page shows "total" or "physical" in type column. 

### Expected behavior
Either we need to disable type column in UI or we need backend API change to display valid "virtual" or "physical" type.

#### Steps to reproduce
1. Navigate to openshift page

### Additional context, version info
![Screenshot from 2020-11-03 20-11-32](https://user-images.githubusercontent.com/16951913/97999434-4ffa1980-1e11-11eb-926f-44ba7ccf9fe9.png)

**Comment by cdcabrera** [comment]
Indeed, GUI is just passing an unrecognized string
  
![Screen Shot 2020-11-03 at 10 33 40 AM](https://user-images.githubusercontent.com/3761375/98006311-14832f00-1dc0-11eb-8496-b4960390a12b.png)

**Comment by ntkathole** [comment]
@kahowell ^

**Comment by ntkathole** [comment]
We can close this issue. It is taken care via ENT-3225
