### ISSUE TITLE
Screen adjustments may leave blank space on page

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#501]
## Description
On some screen adjustments (minimize and maximize), page may leave blank space. I think this is very rare case and minimal priority issue. On page refresh, everything looks good.

**I see this is not new behavior. It is also reproducible on prod as well.**

### Expected behavior
Screen should adjust correctly without refresh. 

#### Steps to reproduce
1. Open subscription watch page (original screen size).
2. Minimize screen.
3. Maximize screen.
4. Apply any filter.
5. See blank page left in between graph and system table.

### Additional context, version info
![min-max-screen](https://user-images.githubusercontent.com/16951913/98633290-195b5c00-2347-11eb-9e09-604753be37b9.gif)

**Comment by cdcabrera** [comment]
Relates to #492

**Comment by ntkathole** [comment]
Fixed!
