### ISSUE TITLE
Implement inventory enhancements for duplicate entries

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#504]
## Description

As a UI/UX person I need to consider how to display duplicate entries around the hypervisor measurement type, specifically when it's a RHEL system and registered hypervisor.

## Acceptance Criteria
- [ ] Storyboard for displaying total and breakout
   - [ ] GUI implementation

## Assumptions and Questions

- Relates to API issues `ENT-3210`

**Comment by cdcabrera** [comment]
As of 20210104 this needs to be resolved on the API

**Comment by kahowell** [comment]
FYI, we discussed in grooming the additional need for a flag for "bad hypervisor" (e.g. 0 sockets reported).
