### ISSUE TITLE
Activate Satellite for left nav, display fixes

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#539]
## Description
As a developer I need to update the Platform left menu config to activate the left navigation for ~Satellite 6~ Satellite and Satellite Capsule and Server ~Satellite 6 Capsule~.

## Acceptance Criteria
- [x] Platform config updated
   - initial CI-beta PR
   - QA, and related prod PRs
- [x] Strings for Sat Capsule & Server updated #540 #542  #553
- [x] "Clear" state behavior fixed #541 

## Assumptions and Questions
- relates #524
- there are currently strings around the title for Capsule that need to be updated, they are lengthy. we may be able to hold and wait for further updates

**Comment by ntkathole** [comment]
Adding just for a record, this needs api fixes https://issues.redhat.com/browse/ENT-3447 and https://issues.redhat.com/browse/ENT-3363

**Comment by cdcabrera** [comment]
resolved on 20220914 https://github.com/RedHatInsights/cloud-services-config/pull/1287
