### ISSUE TITLE
Missing clear all filters button on satellite page

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#541]
## Description
Missing clear sla/usage filters button on satellite page.
#539 

### Expected behavior
"Clear all filters" button to clear sla/usage filters.

#### Steps to reproduce
1. Navigate to https://qa.cloud.redhat.com/beta/subscriptions/satellite-sw/capsule and select filters

### Additional context, version info
![Screenshot from 2020-12-15 09-03-22](https://user-images.githubusercontent.com/16951913/102167710-f1669780-3eb4-11eb-90eb-633a37ef1b4e.png)

**Comment by cdcabrera** [comment]
Note for dev... 

Looks like a solution is around how we manipulate state and "connecting" the new productView component vs directly connecting on productViewSatellite. 

An alternative would be to evaluate how we do this... consider not funneling the filter query through the view but directly on the toolbar, or subsequent component similar to #476

**Comment by ntkathole** [comment]
Fixed!
