### ISSUE TITLE
system table page navigation is broken

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#546]
## Description
System table page navigation is broken. Could not naviagte to previous page as back button is disabled and numbers not shown currently in table. (see screenshot attached)

### Expected behavior
Correct page navigation and system table numbers. 

#### Steps to reproduce
1. Reproducible in CI-beta only.
2. Navigate to https://ci.cloud.redhat.com/beta/subscriptions/rhel-sw/all
3. Navigate to 2nd page and try to click on previous page button to navigate back.
4. Button is disabled.

### Additional context, version info
![Screenshot from 2021-01-11 20-34-44](https://user-images.githubusercontent.com/16951913/104199303-48787180-544d-11eb-8259-69f62d983483.png)

**Comment by cdcabrera** [comment]
As of 20200111 on our local proxy run we rolled back recent changes all the way to #538 the last of the Dec updates and the issue still persists. At the moment this coming across as not on the Curiosity side, but something else possibly platform or api, we'll keep looking

**Comment by cdcabrera** [comment]
@ntkathole this should be ready for confirmation now

**Comment by ntkathole** [comment]
Fixed! Thanks :+1:
