### ISSUE TITLE
Add max character validation for display name filter search box

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#569]
## Description
As there is no limit on adding content to search box, user can enter any number characters which leads to 400 request on host list.

There is no adverse effect as application works fine after page refresh.

### Expected behavior
Limitation of characters on user input.

#### Steps to reproduce
1. Navigate to subscription watch.
2. Add around 3k English characters in search box of filtering name.

### Additional context, version info
![Screenshot from 2021-02-01 15-27-16](https://user-images.githubusercontent.com/16951913/106443482-898b0100-64a2-11eb-8491-5a3bb9f6c805.png)

**Comment by cdcabrera** [comment]
So this probably needs to be a 2 part correction, GUI and API.

GUI can place a cap, but said limit can be bypassed. Is there an average name size that would be helpful @ntkathole ?

**Comment by ntkathole** [comment]
> So this probably needs to be a 2 part correction, GUI and API.

@kahowell can help us here in terms of api if having limit will help or the request will be rejected from other service before that our validation. 

> GUI can place a cap, but said limit can be bypassed. Is there an average name size that would be helpful @ntkathole ?

I vote for 255 characters (https://access.redhat.com/solutions/2412), that's also for satellite 6/foreman team use, but I think that's topic for grooming or platform people.

**Comment by ntkathole** [comment]
Fixed!
