### ISSUE TITLE
PatternFly Charts  - Review Updates

### ISSUE THREAD

**Issue by priley86** [RedHatInsights/curiosity-frontend#66]
## Feature description

As part of the #51 (PatternFly Phase 1 Review), I noted that our current usage of PF Stack Chart can potentially be improved.

* update PF & PF React-Charts dependency (and test new theme)
* Use StackChart's API as indicated in the following new "Monthly Usage" example coming to PatternFly (and include Chart Axis api usage). This should allow us to remove `nth-child`/ `display:none` CSS
* Potentially look to adopt responsive `clientWidth` instead of fixed breakpoint sizing (needs testing)
* Ensure all existing functionality is retained 

PF responsive Stack Chart reference:
https://github.com/patternfly/patternfly-react/pull/2625/files

### Is your feature request related to a problem?

...

## Acceptance Criteria
- [ ] Verify that PF usage is as close to upstream example as possible and meets the UX goals here. This ensures the StackChart can be used by other products in the same fashion.

## Additional context

...

**Comment by cdcabrera** [comment]
Overlap with #51 merging for tracking
