### ISSUE TITLE
graph overflow X axis scroll for smaller screens?

### ISSUE THREAD

**Issue by bclarhk** [RedHatInsights/curiosity-frontend#74]
## Description
As an end user I would like to be able to view all data points on the graph at smaller screen widths.

## Acceptance Criteria
- [ ] Investigate the need to apply an overflow-x scroll to the display graph at smaller screen widths. 

## Assumptions and Questions
- Would this only apply to the `monthly` dropdown granularity selection out of the possible choices of `daily`, `weekly`, `monthly`
### Proposed wireframe
![RHEL usage v1 daily](https://user-images.githubusercontent.com/32572198/62486426-40fb6600-b78d-11e9-81e6-033ba2989b33.png)

**Comment by cdcabrera** [comment]
As of 20191008 this is no longer part of the storyboard
